### ISSUE TITLE
프로젝트 폴더 관련

### ISSUE THREAD

**Issue by datoybi** [With-Pet-Project/With-Pet-FE#18]
규호님 안녕하세요!
프로젝트 폴더 depth와 naming와 관련하여 의논할게 있습니다

## 1. Floder depth

폴더 뎁스가 깊으면 눈으로 훑는것보다 하나 하나 눌러봐야 파일 위치를 확인할 수 있어서 불편한 것 같고, 가독성도 좋지 않아서 꼭 필요한 경우만 폴더를 만드는게 어떨까요? 

### pages 폴더

pages 폴더 안에 각각의 폴더에 index.js만 넣을텐해서 폴더가 필요할까? 라는 의구심이 들었습니다. 아니면 제가 놓친 다른 이유가 있을까요?

```
// before
with-pet-FE
└─ src
   └─ pages
     ├─ AccountsPage
     │  └─ index.js
     ├─ CommonLayoutPage
     │  └─ index.js
     ├─ CommunityPage
     │  └─ index.js
     ├─ DiaryPage
     │  └─ index.js
     ├─ HospitalPage
     │  └─ index.js
     ├─ LandingPage
     │  └─ index.js
     └─ MyPage
        └─ index.js

// after
with-pet-FE
└─ src
   └─ pages
     ├─ Accounts.js
     ├─ CommonLayout.js
     ├─ Community.js
     ├─ Diary.js
     ├─ Hospital.js
     ├─ Landing.js
     └─ MyPage.js
```

참고한 오픈소스

[https://github.com/velopert/velog/tree/master/velog-frontend/src/pages](https://github.com/velopert/velog/tree/master/velog-frontend/src/pages)

[https://github.com/skidding/flatris/tree/master/web/pages](https://github.com/skidding/flatris/tree/master/web/pages)

---

### Diary 폴더

현재 구현중인 Diary는 파일 구조가 이런식입니다.

```

with-pet-FE
└─ src
    └─ components
     └─ Diary
        ├─ DiaryHeaderContainer
        └─ DiaryMainContainer
           ├─ DiaryMainContainer.js
           ├─ DiaryMainContainer.scss
           └─ sections
              ├─ CenterSection
              ├─ HealthSection
              ├─ SpecialNoteSection
              ├─ WalkingSection
              └─ WeightSection

```

 중간에 DiaryMainContainer나 sections로 폴더로 분기를 해야할까?라는 의문이 들었어요.

```
with-pet-FE
└─ src
    └─ components
     └─ Diary
        ├─ DiaryHeaderContainer
        ├─ CenterSection
        ├─ HealthSection
        ├─ SpecialNoteSection
        ├─ WalkingSection
        └─ WeightSection

```

이런식으로 depth를 줄이는게 어떨까요?

참고 오픈소스

[https://github.com/velopert/velog/tree/master/velog-frontend/src/components/main](https://github.com/velopert/velog/tree/master/velog-frontend/src/components/main)

[https://github.com/oldboyxx/jira_clone/tree/master/client/src/Project/Board](https://github.com/oldboyxx/jira_clone/tree/master/client/src/Project/Board)

---

컴포넌트의 세부 컴포넌트는 폴더를 만들어 그 안에 넣는게 좋을것 같습니다. 구현중인 CenterSection으로 예를 들자면
![화면 캡처 2023-02-01 123829](https://user-images.githubusercontent.com/41810621/215951987-80aecc13-0527-434f-a9d1-7b1a83b435a7.png)

이런식으로 나눌 수 있을 것이고, 폴더 형태는 이렇게 만드는게 어떨까요?

```
with-pet-FE
└─ src
    └─ components
     └─ Diary
          └─ CenterSection
            ├─ Calender
            │  ├─ Calender.js
            │  ├─ Calender.scss
            │  └─ DateBox
            │      ├─ DateBox.js
            │      └─ DateBox.scss
            └─ Challenge
                   ├─ AchievementRate
                   │  ├─ AchievementRate.js
                   │  └─ AchievementRate.scss
                   ├─ Challenge.js
                   ├─ Challenge.scss
                   └─ Goals
                      ├─ Goal
                      │   ├─ Goal.js
                      │   └─ Goal.scss
                      ├─ Goals.js
                      └─ Goals.scss
         
```

참고 오픈소스

[https://github.com/oldboyxx/jira_clone/tree/master/client/src/Project/Board/Lists/List](https://github.com/oldboyxx/jira_clone/tree/master/client/src/Project/Board/Lists/List)

[https://github.com/adrianhajdin/project_chat_application/tree/master/client/src/components/Messages/Message](https://github.com/adrianhajdin/project_chat_application/tree/master/client/src/components/Messages/Message)

아니면 관련 component를 나열하는 방법도 있네요

[https://github.com/velopert/velog/tree/master/velog-frontend/src/components/post](https://github.com/velopert/velog/tree/master/velog-frontend/src/components/post)

---

## 2. naimg

혹시 Container로 이름을 통일한 이유가 나중에 구현할 때 다른 의미가 있어서 그렇게 하신건가요?

```
with-pet-FE
└─ src
   ├─ App.css
   ├─ App.js
   ├─ components
   │  ├─ common
   │  │  ├─ Header
   │  │  │  ├─ HeaderContainer.js
   │  │  │  └─ HeaderContainer.scss
   │  │  ├─ Logo
   │  │  │  ├─ LogoContainer.js
   │  │  │  └─ LogoContainer.scss
   │  │  ├─ Modal
   │  │  │  └─ ModalContainer.js
```

그렇지 않다면 Section, Container라는 말을 사용하는 대신 이름에서 충분히 Section과 Container가 표출되게끔 폴더명을 정의하는게 어떨지 싶어요. CenterSection을 예로 들자면..

```
with-pet-FE
└─ src
    └─ components
     └─ Diary
          └─ Challenge // CenterSection (어디가 중앙의 section인지 모호.. 더 좋은 네이밍이 생각이 안나네요)
            ├─ Calender
            │  ├─ Calender.js
            │  ├─ Calender.scss
            │  └─ DateBox
            │      ├─ DateBox.js
            │      └─ DateBox.scss
            └─ ChallengeList 
                   ├─ AchievementRate
                   │  ├─ AchievementRate.js
                   │  └─ AchievementRate.scss
                   └─ Goals
                      ├─ Goal
                      │   ├─ Goal.js
                      │   └─ Goal.scss
                      ├─ Goals.js
                      └─ Goals.scss
```

이런식으로요!

---

폴더명이 Community인데 또 Community를 명시하는 이유가 있을까요?

```
// before
├─ Community
│  ├─ CommunityHeaderContainer
│  │  ├─ CommunityHeaderContainer.js
│  │  └─ CommunityHeaderContainer.scss

// after
├─ Community
│  ├─ Header
│  │  ├─ Header.js
│  │  └─ Header.scss

```

참고해볼 리엑트 오픈소스

[https://github.com/adrianhajdin/project_chat_application](https://github.com/adrianhajdin/project_chat_application)

[https://github.com/velopert/velog](https://github.com/velopert/velog)

[https://github.com/oldboyxx/jira_clone/tree/master/client/src/Project/Board](https://github.com/oldboyxx/jira_clone/tree/master/client/src/Project/Board)

[https://github.com/skidding/flatris/tree/master/web/constants](https://github.com/skidding/flatris/tree/master/web/constants)

---

제가 의논하고 싶은 부분은 이정도입니다.
궁금한 점 있으시면 연락주세요!

<br/>

**Comment by cgh0524** [comment]
질문 감사합니다. 디렉토리 구조를 상의하다보니 기간이 길어져서 일단 구조를 만들어놓고 의논하는게 좋을 것 같아 제 스타일대로 짜다보니 의문점이 많이 생기신 것 같습니다.

최대한 답변을 드린다고 했는데. 이해가 되셨을지 모르겠습니다. 이건 순전히 그냥 제가 이렇게 한 이유와 입장에 대해서 설명을 드린 것이라 읽어보시고 말씀해주세요

## 1. Folder Depth
### 1-1. pages 폴더
저는 파일이 길게 나열되어 있는 것보다 폴더로 넣어 놓는 것이 가독성이 좋은 것 같아서 폴더로 나누는 것을 선호합니다. 그리고 추후에 각 page관련 추가 파일들이 필요할 수도 있기에  미리 나눠놓는 편입니다.

예를 들어 RegisterPage와 LoginPage가 대부분의 요소를 공통적으로 갖고 있고, `RegisterPage = LoginPage + 추가정보 기재`의 형태라면 `AuthPage폴더`안에 공통된 Form을 분리하여 `AuthPage` 만들고 `AuthPage/LoginForm`과  `AuthPage/RegisterForm`로 나눌 수 있으니까요.

만약 한 페이지라도 폴더가 생기면 모두 폴더로 통일하는게 가독성이 좋을 것 같아서 폴더로 나눠놨습니다. 추후에 추가 파일이 생기지 않는다면 다솜님 말씀대로 폴더는 없애도록 하겠습니다. 




### 1-2  Diary 폴더
폴더가 너무 많아서 depth가 깊어지는 것을 우려하시는 것 같습니다. 폴더를 많이 나눈 이유는 폴더를 나누지 않았을 경우 나는 A파일만 보고 싶은데 B, C, D까지 길게 나열되는 것을 좋아하지 않아서 그렇습니다. 

MainContainer폴더가 없다면 Diary폴더를 여는 것만으로
- DiaryHeaderContainer 폴더
- DiaryMainContainer.js
- DiaryMainContainer.scss
- CenterSection
- HealthSection
- WalkingSection
- WeightSection
이 나열됩니다.

제가 주로 참고하는 디자인 패턴이 `Presentational & Container 패턴, Atomic Design 패턴` 정도인데 셋을 비교해보면 프로젝트가 커지면서 파일 갯수가 늘어나며 길게 나열되거나, depth가 깊어지는 것은 피할 수 없는 문제인 것 같습니다. 물론 그 중간점을 잘 찾는 것이 중요하니 이 부분은 다솜님이 보시기에 가독성이 문제가 된다면 말씀해주세요.

++ Diary페이지를 보니 여러 section들로 나눠지기에 일단은 sections폴더를 만들고, 추후에 section이외에 추가로 분리하여 구현할 동급의 컴포넌트들(Footer 같은 것들)이 생길 수 있기에 미리 나눴습니다. 다만 아직 페이지 완성 단계가 아니기에 구현이 어느 정도 끝나면 필요에 따라 리팩토링하여 정리할 수 있는 부분인 것 같습니다.


### 1-3  컴포넌트의 세부 컴포넌트는 하위폴더로  만드는게 어떨까요?
이미 적용중인 방식입니다. 어제 그렇게 폴더 정리해서 올려드렸는데 커밋내역이나 PR올릴 때 제가 설명이 부족했던 것 같습니다. 아니면 혹시 다솜님이 올려주신 대안을 잘못 이해한 부분이 있을 것 같습니다. 확인해보시고 알려주세요.

<br>

## 2. Naming

### 2-1. Container
별 다른 의미는 없고 상위 페이지 => 하위 컴포넌트 순으로 페이지를 분리하다보니
`item`들을 담는 상위 컴포넌트들에 `Container`라는 의미로 붙여습니다. 
`Section`도 마찬가지로 이 폴더가 지금 어느 수준의 컴포넌트들을 담고 있는지 나타낼 필요가 있다고 느껴서 붙였습니다. 너무 난잡하게 느껴진다면 Section, Container와 같은 접미사들은 제거하도록 하겠습니다.

달력과 Challenge가 동일 단계의 다른 기능인지, 달력 자체가 Challenge에 포함되는 하위 기능인지 제가 인지를 제대로 못한 것 같습니다. 

만약 Calendar가 단순히 Challenge관리를 위한 Calender라면 CenterSection이 아닌 ChallengeSection으로 고쳐야할 것 같습니다. 

### 2-2. 폴더명이 Community인데 또 Community를 명시하는 이유가 있을까요?
저는 이름이 길어지더라도 각각의 폴더와 파일 한개만 봐도 이게 어디속했는지 알 수 있는 것을 선호하는 편입니다. 

그리고 모듈화하여 import 할 때도 `CommunityHeader`와 같은 방식으로 import 해주는 것이 구분하기 좋다고 생각하는데 이왕이면 파일명와 모듈명이 같다면 좋을 것 같아서 그렇게 해주고있습니다.

올려주신 오픈소스들을 봤는데
`Main/MainHead/MainHead.js`로 저와 비슷한 방식으로 한 것 같습니다만 혹시 어느 부분을 봐야할까요...?

**Comment by datoybi** [comment]
코멘트 감사합니다. 규호님 코멘트를 토대로 관련 이슈들 다시 한번 생각해 보았습니다.

# 해결된 사항

## 1-1

규호님이 제시한 예시와 찾아보니 page 폴더는 그냥 두는편이 좋을 것 같네요! 

## 2-2

아 이부분도 자세히 찾아보니 스타일 인 것 같네요~ 이 부분은 유지하는 쪽이 좋을 것 같습니다!

---

# 더 생각해보기

## 1-2

저는 한 폴더에 저정도 있는건 전혀 문제가 되지 않는다고 생각하긴 합니다 그런데 만약 headerContainer나 MainContainer가 있으면 MainContainer안에 Header 폴더만 없어지는거 아닌가요??🤔

음.. sections폴더 만들고 그 안에 넣는 형태로 구현하는 건 사실 본적이 없긴 합니다..! 

## 1-3

넵 잘 지켜지고 있는 부분이나 확실히 하고자 작성했습니다. 그런데 저렇게 정리를 해두면 section이나 container라는 이름이 굳이 필요할까 싶었어요. 폴더 한번 열때마다 관련된 세부적인 컴포넌트인걸 직관적으로 알게되니까 굳이 관련 명칭을 사용할 필요가 없다고 생각했거든요. 

예를 들어 Diary폴더를 열면 Health, SpecialNote, Walking, Weight, Center 이런 큰 컴포넌트들이 있다는걸 알수 있고, 그 중에 Center폴더를 열면 Calender, Challenge가 크게 나눠진다는 걸 알 수 있으니까요. 그래서 제 생각은 오히려 headerContainer나 sections로 나눠놓으면 방금 얘기한 폴더 안에 컴포넌트를 직관적으로 볼 수 있게 하는 걸 방해한다고 생각했습니다. 

## 2-1

아~그렇네요 달력이 또 쓰일수도 있군요.. 그 경우까지는 생각을 못했어요. 저의 예시는 Calender는 단순히 Chellenge안의 컴포넌트 였습니다.

section이라는 명칭(ChallengeSection)을 사용하는 이유가 Diary의 최상단 컴포넌트 임을 명시하려 하는것 같은데.. 맞나요?! 그렇다면

- Section이란 명칭은 유지하기
- Container 명칭은 삭제하기
- sections 폴더, headerContainer폴더, MainContainer폴더는 삭제하기

어떤가요?!

---

규호님은 모든 정보를 알 수 있는 파일명을 좋아하는 것 같고, 저는 폴더별로 정리된 눈에 띄는 파일명을 좋아하는 것 같네요! 

궁금하신 점이나 의견 있으시면 편하게 말씀해주세요.

**Comment by cgh0524** [comment]
## 1 - 2
Header같은 경우, Main과 다른 부분으로 분리하기도 했고. css도 따로 관리를 해줘야 할 것 같습니다. 게다가 Diary나 Community페이지의 Header는 server-state data를 가져오거나 mutation으로 보내주는 경우도 있기 때문에 hooks관련 파일들도 늘어날 예정이라서요. 추후에 test코드를 작성하게 된다면 파일은 더 늘어날 수도 있을 것 같습니다.
이 부분은 딱 정해놓기보다는 페이지 특성따라 맡은 사람 재량에 맡기는 게 좋을 것 같습니다. 

다만 
- `Header`
- `Main`
- `ChallengeSection`
- `HealthSection`
- `WeightSection`
- `WalkingSection`
으로 동일 level에 정렬한다면 section쪽 depth는 한 단계 줄일 수 있을 것 같습니다.


## 2 - 1
뒤에 접미사 비슷하게 붙이는게 확실히 난잡하게 느껴질 수 있을 것 같습니다.

- CenterSection : 일단은 ChallengeSection으로 수정했습니다. 추후에  필요하다면 다른 명칭으로 바꾸는게 좋을 것 같습니다.
- Container 삭제
- Section 명칭 유지
- Section폴더 삭제
- Main, Header 유지(다이어리 페이지 안에서는), section들을 Main에서 꺼내 동일 level에서 관리

가 어떨까요?

**Comment by datoybi** [comment]
네 제안해 주신 부분 다 잘 정리가 된것 같습니다. 
더이상의 궁금증이 없다면 이만 close 하겠습니다👍
