### ISSUE TITLE
git workflow, CI/CD 관련

### ISSUE THREAD

**Issue by cgh0524** [With-Pet-Project/With-Pet-FE#26]
다솜님, 배포 단계에서 API_KEY가 적용되지 않던 문제는 해결했습니다.
문제를 해결하고 보니  git workflow, CI/CD 관련해서 재정립 할 필요성이 있다고 생각하여 이슈 등록합니다.

### 방법 1. 
팀 계정에 초대를 드리면 승인없이 배포가 가능한 것 같습니다. 이 경우, 유료 플랜을 사용해야 가능한 것 같습니다. 
현재 team 계정이 2주가 지나서 무료 플랜으로 유지되고 있습니다.
### 방법 2.
제 개인 repo로 fork하여 변경사항이 있을 때마다 update하여 vercel 개인 계정에 배포하는 것입니다. 이 경우 제가 수동으로 update를 계속 해주어야 합니다. 배포까진 편할 수 있으나 저번처럼 테스팅을 로컬에서만 진행하기 때문에 배포하고 나서야 문제점을 알 수 있습니다.
### 방법 3.
github flow 사용.
지금 사용하고 있는 방법과 비슷하지만, 승인과 테스트 등이 추가될 것 같습니다. 조금 번거롭겠지만 preview에서 테스팅까지 모두 끝낸 뒤 배포까지 안전하게 할 수 있을 것 같아요.

<br><br>

## github flow 관련 참조 링크(한 번 읽어보시고, 밑에 글 읽어주세요.)
[1번 링크](https://ujuc.github.io/2015/12/16/git-flow-github-flow-gitlab-flow/)
[2번 링크](https://dogfeet.github.io/articles/2011/github-flow.html)

저는 개인적으로 '방법3'으로 진행하는게 포트폴리오로서 가치가 높아질 수 있다고 생각합니다. 다솜님 생각은 어떠신지 궁금합니다.
다음은 3번처럼 진행하게 된다면 어떻게 하게 될지 적어놓은 글입니다.
그저 설명 드리는 글이니 읽어보시고 의견 주세요.

<br><br>

### 1. Master 브랜치에만 정해진 규칙이 있다.(우리는  production)
- 반드시 규칙을 지켜야 하는 유일한 브랜치( 나머지 브랜치는 유동적)
- Merge전에 충분한 테스트 필요(테스트는 로컬이 아닌 push하고 github action으로 자동화)
- **다음과 같은 Rule을 추가할까 합니다.**
1) `A`가 PR을 올리면 `B`가 review 후, approve and merge, `B`가 개인 브랜치 삭제
2) status check(테스트 통과 상태)가 초록색인 경우만
- 테스팅 코드 작성(선택사항, 필요하다고 느낄경우 작성). 작성한 파일이 하나도 없을 경우 적당히 통과될만한 코드 작성해서 push해주세요.

### 2. 브랜치는 항상 Master(production) 브랜치에서 만든다.
- `git switch 브랜치명`
- 브랜치명은 어떤 브랜치인지 명확하게 나타나도록 짓는다.
ex) fix/hospital 처럼 현행유지하고 개인 브랜치에push를 자주해주는게 좋을 것 같습니다.

### 3. 개인 브랜치는 자주 push한다.
- 서로의 진행상황을 공유할 수 있도록 자주 push한다.

### 4. 언제든지 Pull Request한다.
- Merge할 때만 하는 것이 아니라 도움이나 피드백이 필요할 때에도 Pull Request
- 제목을 `도움이 필요해요`, `검토해주세요`, `Merge해주세요` 등등 다양한 목적으로 활용.

### 5. Pull Request로 리뷰한 후에만 Merge한다.
리뷰 필수, 테스팅 코드 작성한 경우 테스팅 통과 필수

### 6. 일단 production에 Merge하면 바로 deploy.
vercel로 자동 배포.

## Github Action 파일 설명
`github action`을 이용해서 자동 배포와 테스팅 코드를 작성했습니다.
`github action` 관련 파일의 위치는  `.github/workflows`안에 `yaml`파일로 작성됩니다.
파일별 설명은 주석을 참고해주세요.

### preview.yaml
![image](https://user-images.githubusercontent.com/68717963/216400301-5185a6e8-3822-4ec8-b803-ef700cd351ee.png)

###  production.yaml
![image](https://user-images.githubusercontent.com/68717963/216400864-4c428924-8188-4991-b49e-0f0b2965bbfa.png)

### cypress.yaml
![image](https://user-images.githubusercontent.com/68717963/216402240-7d44e45c-4a09-46c0-af71-440dc204bd86.png)

- cypress cloud의 record는 매달 무료 횟수가 500회(?)정도로 제한되어 있어서 테스트가 실패한 경우 확인을 위해서만 true로 확인 후, 통과되면 false로 바꾸기.

### cypress.yaml `CYPRESS_BASE_URL` 관련설명
위 코드에서 `CYPRESS_BASE_URL`의 경우 배포될 타깃 URL이 CYPRESS의 환경변수로 등록됩니다.
그래서 테스팅 코드 작성 시 다음 사진과 같이 작성하시면 원래는 되어야 합니다.
![image](https://user-images.githubusercontent.com/68717963/216410729-84d1ca96-ec59-4dd7-a747-d3b9c4c475d3.png)

하지만 저희가 카카오 api를 사용하고 있는 것이 문제가 됩니다. 사이트 도메인을 등록해주어야 카카오 API가 정상적으로 작동하는데 `preview 배포`특성상 url이 가변적인데다가 `github action으로 작성된 target url`의 경우 난수화된 url이 들어갑니다. 난수화된 url로 배포가 성공하면 우리가 알아볼 수 있는 url이 하나 더 생성됩니다.
아래 사진을 봐주세요.
![image](https://user-images.githubusercontent.com/68717963/216420299-a15135a8-6b05-418f-b1a8-ec5e3297ce04.png)
`DOMAINS`의 두번째 url이 난수화된 `preview URL`, 첫번째 URL이 cy.visit()에 작성하고, 카카오 사이트 도메인에 작성해야할 url입니다.

#### 다솜님의 preview url
 `https://with-pet-fe-git-fork-datoybi-[A]-[B]-with-pet-prod.vercel.app`
- 다솜님이 push한 브랜치명이 `feat/hospital`일 경우 `[A]`는 feat, `[B]`는 hospital입니다. 
- 이 url은 push한 브랜치가 삭제되기 전까지 유효합니다.
- 카카오 API를 테스트하는 경우, `카카오 디벨로퍼스`에서 사이트 도메인을 수시로 등록해주소 cy.visit()안에도 위의 url을 입력해주어야 합니다. 
- 사이트 도메인의 경우 vercel에 제 카카오 api를 등록해놓아서, 제가 등록한 어플리케이션으로 초대를 드려 다솜님에게 수정 권한을 드리겠습니다. 
- 카카오 API를 테스트하는 코드가 없을 경우, 백틱을 사용하여 ${Cypress.env('BASE_URL')}사용하시면 됩니다.

## Github flow 요약
1. production branch - branch rule 추가
- PR review => approve => merge => 브랜치 삭제
- merge할 개인 브랜치는 CI(Continuous Integration)을 통과한 브랜치일 것.
2. 개인 브랜치는 push 자주하기.
3. 테스팅을 한다면 무조건 push하여 진행, 로컬에서의 테스트는 원한다면 추가로 하기.
4. 개인 브랜치 이름 구체적으로 명확하게
5. PR은 merge뿐만 아니라 목적이 있는 경우 자주하기

**Comment by datoybi** [comment]
규호님 잘 보았습니다! 몇가지 질문 사항이 생겨 질문드려요~

### vercel 배포

지금 vercel 플랜 유지하되, git flow 방법론을 따라서 서로 PR올리면 체크, 승인해주고 브랜치 삭제해주고, 결국 최종적으로 규호님이 승인을 해주어야 배포가 되는 형식을 따르자는 말씀인가요? 아니면 저도 승인이 가능한가요?

명시해둔 github flow 따르는 건 찬성입니다.

### cypress 테스팅

`cypress cloud의 record는 매달 무료 횟수가 500회(?)정도로 제한되어 있어서 테스트가 실패한 경우 확인을 위해서만 true로 확인 후, 통과되면 false로 바꾸기.`

이 부분은 지금처럼 테스트 코드 작성 후 PR 올리고, 테스트 코드가 실패하면 record를 true로 바꾸고, cypress 테스팅 코드 수정 후 재검사를 한다. 그러고 통과하면 record를 false로 바꾸라는 말인거죠!?

### github flow

개인 레포의 production도 자주 upstream에서 PULL, branch에서 push 해야할까요? (아직 branch따서 구현중인 경우..)

---

kakao api cypress tesing 경우 텍스트로는 이해했는데 직접 조만간 시도해봐야겠네요

**Comment by cgh0524** [comment]
### Vercel 배포
Vercel 배포 관련해서는 제가 팀계정에 초대를 못드려서 매번 승인을 해드려야 할 것 같습니다.  
E2E testing 같은 경우에는 일단 `preview`버전이 배포가 되어야 이에 대해서 테스팅이 가능하기 때문에 push하실 때마다 제가 바로바로 승인해드려야 할 것 같습니다...
(이 부분은 메일 알람 해놓고 제가 계속 확인하겠습니다)

다만 production branch에 merge할 경우에는 제가 작성한 코드는 다솜님이 승인하셔야 하고. 다솜님이 작성하신 코드는 제가 승인해야 합니다. merge 와 브랜치 삭제는 승인하는 사람이 하면 됩니다.

### Cypress Testing
넵. 다음 push에서 record할 필요가 없다면 push전에 `record: false`로 바꿔서 push하시면 될 것 같아요. (push전에만 한 번씩 확인해주시면 될 것 같습니다.)

### github flow
production의 경우 어차피 제가 작성한 코드는 다솜님이 리뷰 후 승인, merge까지 해주셔야 하기 때문에 자주하실 필요는 없을 것 같습니다. 
merge를 위한 PR올리시기 전에만 한 번 하시면 될 것 같습니다.
(push를 자주하자는 이유는 단순히 서로의 진행 상황을 git에서 확인하기 위한 목적입니다.)

### kako api key같은 경우 vercel에 저의 키를 등록해놓았기 때문에 `카카오 이메일 아이디` 알려주시면 사이트 도메인 수정하실수 있도록 제가 초대드리겠습니다.
