### ISSUE TITLE
에러 핸들링 시나리오

### ISSUE THREAD

**Issue by datoybi** [With-Pet-Project/With-Pet-FE#45]
# 에러 핸들링 시나리오

## 누구에게 어떻게?

- **유저**
    - toast 표출해주어 에러 사실을 알려준다.
    - 다시시도 버튼을 통해서 새로고침을 하게끔 유도한다
- **개발자**
    - 개발 환경에서 에러 발생시 console.error()로 알려주고,
    - 배포 환경에서 에러 발생시 [Sentry](https://sentry.io/)로 알려주어 대응한다

## 에러가 발생할법한 상황?

1. get이 실패한 상황
    페이지에 “데이터를 로드하는데 실패했습니다. 다시 시도해주세요.”라는 문구와 새로고침 버튼 표출하기
2. 데이터 변경 HTTP 메서드가 실패한 상황 (post, patch, delete)
    페이지는 유지하되, 다시 시도해달라고 toast UI 표출하기
3. 그 외 500대 서버 에러나 네트워크 에러
    페이지에 “예상치 못한 에러가 발생했습니다. 잠시후 다시 시도해주세요.”라는 문구와 새로고침 버튼 표출하기
4. 요청 권한이 없는 상황 (Unauthorized)
    “접근 권한이 없습니다.” 라는 문구와 로그인 버튼 표출하기
5. 없는 페이지를 접근했을 때
    404 페이지를 보여주기

더 생각해봐야할 에러가 있을까요?

## 구현방법
[TkDodo님이 제안한 방법](https://tkdodo.eu/blog/react-query-error-handling) 따르기

1. React-query에서 제공하는 global callbacks를 이용하여 에러가 발생할 때마다 toast를 표출하고
2. [Error Boundary](https://github.com/bvaughn/react-error-boundary)를 이용하여 에러가 발생할 경우 대체 페이지(fallback UI)를 표출
3. API 에러별로 한곳에서 상황에 맞게 처리

일단 이렇게 생각해봤는데 규호님 생각은 어떤가요?

**Comment by cgh0524** [comment]
전체적으로 제가 생각했던 것과 비슷한 것 같습니다. 다만 sentry가 조금 생소하네요...
다솜님이 말씀하신대로 진행해보고 진행 도중에 필요한 부분들만 서로 협의해서 수정하면 될 것 같아요.
<br><br>

## 질문입니다.

1. Sentry의 경우 무료 플랜은 계정 하나로 알림을 보아야 하는 것 같은데 배포 버전 에러 발생 시, 알림을 어떻게 공유할 것인지 궁금합니다.
2. 제가 ErrorBoundary 및 toast메세지 세팅을 제가 해도 괜찮으실까요?

**Comment by datoybi** [comment]
네 저도 sentry는 스터디를 해봐야할것 같아요 관련 질문에 개인적으로 연락드렸으니 close 하겠습니다!
