### ISSUE TITLE
Modal 위치관련 

### ISSUE THREAD

**Issue by cgh0524** [With-Pet-Project/With-Pet-FE#49]
## 현재 저희 모달의 위치가 컨텐츠의 중앙이 아닌 viewport의 중앙에 오게 됩니다.
다음과 같은 문제가 발생합니다.
- 화면 폭이 작아지면 sidebar에 모달이 가려지거나 눈에 띄게 중앙에서 벗어나는 문제.
- sidebar의 너비 변화(열리고 닫히는 문제)에 대한 대응 문제
(sidebar 너비 정보를 state에 담아서 전역적으로 관리할 수도 있지만 조금 과한 것 같아요)

<br><br>

## 해결 방안(Modal이 놓이는 위치 변경 및 css속성 변경)
우선은 context API로 작업해 놓은게 있어서 그 코드를 변경해보았습니다.
<br><br>

### 1.  main 태그 `position: relative`추가

![image](https://user-images.githubusercontent.com/68717963/219937651-d6d5c964-41ab-4329-9d44-9ddd6a274676.png)

<br><br><br>

### 2. main 태그 안에 `Modal 컴포넌트` 추가(main태그 위치를 `CommonLayoutPage`로 옮기면 한 곳에서 관리 가능)
![image](https://user-images.githubusercontent.com/68717963/219937738-a00965e4-48a5-4e76-a596-342fa3783bb2.png)

<br><br><br>

### 3. CSS 스타일

`ModalWrapper`
- 다솜님의 Backdrop과 동일
- `position: absolute` : `position: relative`인 main태그 안에서 움직이도록 하기위해서
![image](https://user-images.githubusercontent.com/68717963/219938125-f1564361-d884-4da0-bffd-408ce15e5447.png)

<br>

`ModalContent`
- 다솜님의 Modal과 동일
- 빨갛게 표시한 부분 추가
- media query의 경우 화면이 좁아지면 scroll바가 생겨서 그에 맞게 위치를 조절하기 위해서 설정해줬습니다.
![image](https://user-images.githubusercontent.com/68717963/219938318-cd876296-7800-4c4a-96f5-ff56e3294f38.png)

<br><br><br>

## 사용할 Modal을 컨텍스트에 등록하기

<br><br>

### 1. import `useModal`
![image](https://user-images.githubusercontent.com/68717963/219938496-140a8f83-6d6f-4fa5-908a-7accba94dfb2.png)

<br><br>

### 2. component를 닫는 함수
![image](https://user-images.githubusercontent.com/68717963/219938546-231dd5e9-2e60-4255-815a-4ec696eca464.png)

<br><br>

### 3. `닫기`를 트리거 하고 싶은 곳에 등록(closeModal의 인자는 내가 닫을 컴포넌트 이름)
![image](https://user-images.githubusercontent.com/68717963/219938608-cf408394-f38a-4645-9dd6-3400bd9a2bd9.png)

<br><br>

### 4. component를 여는 함수
![image](https://user-images.githubusercontent.com/68717963/219938692-73a9150b-a462-49c8-a713-8d7f0fe3dc03.png)

<br><br>

### 5. `열기`를 트리거 하고 싶은 곳에 등록(openModal의 인자는 내가 열 컴포넌트 이름)
![image](https://user-images.githubusercontent.com/68717963/219938758-a6597da5-70e5-4305-bed6-365fe3c34eff.png)

![image](https://user-images.githubusercontent.com/68717963/219938771-2b0e68f3-61f7-4aa8-a586-baf9b8ecd800.png)

<br><br>

**Comment by datoybi** [comment]
디자인 보니 말씀대로 potal을 사용하여 상위에서 표출하는 방식은 부적절한것 같고 main component안에서 관리해야 할 것 같아요!! 규호님이 만든 훅 적용해서 제것도 수정 할게요~
