### ISSUE TITLE
로그인 인증/인가

### ISSUE THREAD

**Issue by cgh0524** [With-Pet-Project/With-Pet-FE#62]
로그인 인증방식 관련해서 프론트엔드, 백엔드 협의가 필요할 것 같아 issuse 등록합니다. @datoybi @Jin409 @Lee-Sang-Min1998 

제가 조사하고 정리한 바로는 다음과 같습니다.

찾아볼수록 다양한 방법이 있는 것 같고 정답이 따로 있는건 아닌 것 같아요.
혹시 잘못된 부분이 있거나 다른 의견이 있다면 제안 부탁드립니다.
<br><br>
### 1. refresh token => 쿠키에 저장
- 서버측에서 쿠키에 httpOnly 옵션 설정, `xss`에 대응
- CSRF로 응답헤더에 refresh token이 삽입되어도 refresh토큰은 access token을 재발급 받는 용도일 뿐이기에 안전. (공격자가 access token탈취하기 까다롭다)
<br><br>

### 2. access token => JSON payload에 저장
- 클라이언트는 access token을 받으면 localStorage에 저장
- 만료시간 짧게 (토큰 탈취되어도 바로 바로 갱신 될 수 있게 하기 위해서)

<br><br>

## 우려 되는 점
요청 한 번에  refresh token과 access token이 함께 들어가 있어 패킷  스니핑같은 공격에 대응 할 수 없습니다. 이를 대비해서 HTTPS를 사용하면 좋긴 한데 이 부분은 공부가 좀 더 필요할 것 같아서 나중에 시간적 여유가 된ㄷ다면 고려해보는게 좋은 것 같아요.

<br><br>

**Comment by Jin409** [comment]
저는 규호님 의견에 따라 처리하면 될 것 같습니다! 다만 `브라우저가 자동으로 header에 refresh token을 담은 header를 삽입.` 이 부분이 잘 이해가 가지 않는데 추가적으로 설명 가능하실까요?

**Comment by datoybi** [comment]
규호님 의견을 수렴해서 제가 찾아본 바를 정리해 보았는데 이런 흐름으로 가면 될까요?

1. 프론트앤드 
    - ID, 비밀번호를 입력한다.
        - email과 pwd를 POST API(/user)를 호출한다.
2. 백앤드 
    - ID와 비밀번호를 DB와 비교하여 검증한다.
    - AccessToken과 RefreshToken, AccessToken의 만료시간을 반환해준다. `(의논할 점 :  AccessToken의 만료시간까지 백앤드에서 받을지, 프앤에서 decode해서 시간 도출할지)`
    - 이때 생성한 RefreshToken은 DB에 {ID, RefreshToken}으로 저장한다.
3. 프론트앤드
    - 반환받은 AccessToken, RefreshToken, AccessToken의 만료시간을 저장한다.
        - RefreshToken은 cookie에 저장
        - AccessToken은 LocalStorage에 저장
        - AccessToken의 만료시간도 LocalStorage에 저장
    - 반환받은 AccessToken을 매 api 호출마다 헤더에 붙여서 전송한다.
        - 필요한 요청의 header에 accesstoken을 같이 보내주는 세팅을 한다.
4. 백앤드
    - api 호출시 헤더의 AccessToken을 확인하고 유효한지, 만료기간이 지났는지 체크 후 api를 동작한다.
    - 만료기간이 지났으면 error?! `(아니면 refresh token이 오염되었으면 error..?)`
5. 프론트앤드
    - API가 실행될 때마다 매번 Access Token의 만료시간을 체크하여 AccessToken의  만료기간이 1분 미만으로 남았다면, RefreshToken을 붙여 백앤드 API Reissue 요청을 보낸다. 
6. 백앤드
    - Reissue 요청이 들어올 경우, RefreshToken이 DB에 있는것과 맞는지 확인한다.
    - 맞다면 새로운 AccessToken과 새로운 AccessToken의 만료 시간을 반환한다.
7. 프론트앤드
    - Reissue 결과 반환된 AccessToken과 만료기간을 LocalStorage에서 갱신한다.

제가 놓친 부분이 있다면 알려주세요

**Comment by cgh0524** [comment]
@Jin409 

서버쪽에서 쿠키를 보내주면 프론트쪽에서는 브라우저 따라 다르긴 한데 프론트에서 설정을 하지 않아도 요청 헤더에 쿠키를 자동으로 담아주는 부분을 말씀드린거에요. 그런데 아마 크롬은 또 자동으로 안담아주는 것 같아서 프론트에서 수동으로 담아줘야 할 것 같긴 합니다.

**Comment by Jin409** [comment]
> 규호님 의견을 수렴해서 제가 찾아본 바를 정리해 보았는데 이런 흐름으로 가면 될까요?
> 
> 1. 프론트앤드
>    
>    * ID, 비밀번호를 입력한다.
>      
>      * email과 pwd를 POST API(/user)를 호출한다.
> 2. 백앤드
>    
>    * ID와 비밀번호를 DB와 비교하여 검증한다.
>    * AccessToken과 RefreshToken, AccessToken의 만료시간을 반환해준다. `(의논할 점 :  AccessToken의 만료시간까지 백앤드에서 받을지, 프앤에서 decode해서 시간 도출할지)`
>    * 이때 생성한 RefreshToken은 DB에 {ID, RefreshToken}으로 저장한다.
> 3. 프론트앤드
>    
>    * 반환받은 AccessToken, RefreshToken, AccessToken의 만료시간을 저장한다.
>      
>      * RefreshToken은 cookie에 저장
>      * AccessToken은 LocalStorage에 저장
>      * AccessToken의 만료시간도 LocalStorage에 저장
>    * 반환받은 AccessToken을 매 api 호출마다 헤더에 붙여서 전송한다.
>      
>      * 필요한 요청의 header에 accesstoken을 같이 보내주는 세팅을 한다.
> 4. 백앤드
>    
>    * api 호출시 헤더의 AccessToken을 확인하고 유효한지, 만료기간이 지났는지 체크 후 api를 동작한다.
>    * 만료기간이 지났으면 error?! `(아니면 refresh token이 오염되었으면 error..?)`
> 5. 프론트앤드
>    
>    * API가 실행될 때마다 매번 Access Token의 만료시간을 체크하여 AccessToken의  만료기간이 1분 미만으로 남았다면, RefreshToken을 붙여 백앤드 API Reissue 요청을 보낸다.
> 6. 백앤드
>    
>    * Reissue 요청이 들어올 경우, RefreshToken이 DB에 있는것과 맞는지 확인한다.
>    * 맞다면 새로운 AccessToken과 새로운 AccessToken의 만료 시간을 반환한다.
> 7. 프론트앤드
>    
>    * Reissue 결과 반환된 AccessToken과 만료기간을 LocalStorage에서 갱신한다.
> 
> 제가 놓친 부분이 있다면 알려주세요

이 의견에 대해서 저는 개인적으로 궁금한 점이 있습니다. 백엔드에서는 TokenExpiredException 이 있어서 프론트 측에서 만료되었는지 모르는 상태에서 access Token 을 담아 요청을 보내면 해당 에러가 던져져서 서버 단에서 캐치해서 다시 access Token 을 새로 발급해드릴 수 있어요. 그래서 저는 굳이 만료시간을 서로 전달할 필요가 없다고 생각했는데, 혹시 왜 만료시간을 반환해야 한다고 생각하셨는지 여쭤봐도 될까요?! 혹시 관련해서 참고하신 자료가 있다면 공유해주시면 감사할 것 같습니다!
그리고 제가 참고한 자료에 따르면 서버단에서 Refresh Token 을 직접적으로 반환하고, 클라이언트 측에서도 직접적으로 저장하는 게 아니라 Refresh Token 이 저장된 db index 만 서로 전달하고 저장한다면 보안상으로 더 좋다고 하더라구요. 이건 어떻게 생각하시는지 여쭤보고 싶습니다!
[참고 자료](https://doogle.link/jwt-%ED%98%B9%EC%9D%80-oauth2-%EC%9D%98-refresh-%ED%86%A0%ED%81%B0%EC%9D%84-%EC%96%B4%EB%94%94%EB%8B%A4-%EC%A0%80%EC%9E%A5%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C/)

**Comment by cgh0524** [comment]
@datoybi 

만료시간을 프론트에서 체크할지, 백엔드에서 체크할지 논의가 필요하긴 할 것 같아요.
근데 제가 생각했던건  `axios.interceptor`라는 것을 사용하는 것이었어요.

1. 프론트가 요청을 보낸다
2. 백엔드가 토큰을 확인하고 만료되면 갱신된 토큰을 보낸다.
3. 프톤트가 `axios.interceptor`를 사용해서 요청을 미리 확인한다. 
3-1. 토큰이 갱신된 경우 그 토큰을 이용하여 `axios.interceptor`가 다시 요청을 보낸다.
3-2. 토큰이 만료가 되지 않아서 정상적인 응답이 왔다면 그 데이터를 사용한다.

이런식으로 생각을 하고 있었어요.

**Comment by Jin409** [comment]
> @datoybi
> 
> 만료시간을 프론트에서 체크할지, 백엔드에서 체크할지 논의가 필요하긴 할 것 같아요. 근데 제가 생각했던건 `axios.interceptor`라는 것을 사용하는 것이었어요.
> 
> 1. 프론트가 요청을 보낸다
> 2. 백엔드가 토큰을 확인하고 만료되면 갱신된 토큰을 보낸다.
> 3. 프톤트가 `axios.interceptor`를 사용해서 요청을 미리 확인한다.
>    3-1. 토큰이 갱신된 경우 그 토큰을 이용하여 `axios.interceptor`가 다시 요청을 보낸다.
>    3-2. 토큰이 만료가 되지 않아서 정상적인 응답이 왔다면 그 데이터를 사용한다.
> 
> 이런식으로 생각을 하고 있었어요.

@datoybi

제가 생각한 방식이 맞을까요?

예를 들어, pet 을 등록하는 요청을 보냈다고 가정한다면

case 1. access token이 만료된 경우
-> 서버 단에서는 pet 을 저장했다는 응답이 아닌 새로운 access token 을 보낸다.
-> 이 경우 axios.interceptor 가 동작해서 새로운 access token 을 갖고 요청을 다시 보낸다.

case 2. access token 이 만료되지 않은 경우
-> 서버 단에서는 저장했다는 응답을 보낸다.
-> axios.interceptor 가 동작하지 않는다.

이렇게 되면 개인적으로 저는 프론트 측에서 만료시간을 저장할 필요가 없다고 생각합니다. 왜냐하면 프론트 측에서 만료시간을 가져야 하는 이유가 만료된 경우 요청을 보내기 전에 만료까지 남은 시점을 확인하고 새로운 access token 을 요청하기 위해서라고 생각하는데, 이를 intercetptor 가 알아서 처리해주니 필요 없지 않을까요? 제가 아직 완벽히 이 프로세스를 체화한 것은 아니고, 클라이언트 측에서도 어떻게 코드가 진행되는지 정확히 아는 것은 아니라서 틀린 의견일 수도 있으니 잘못 생각하고 있으면 지적해주세요!

**Comment by datoybi** [comment]
아 네 두분 말씀대로 구현하면 될 것 같네요 어느정도 방향이 잡힌것 같아요 
백엔드에서 만료시간을 catch 해준다면 만료 시간은 따로 받을 필요는 없을것 같아요!
